# These are supported funding model platforms

github: [afzalimdad9] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: afzalimdad9 # Replace with a single Patreon username
open_collective: afzalimdad9 # Replace with a single Open Collective username
custom: ['https://paypal.me/afzalimdad9'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
